//db.planets.remove()
db.planets.insert({"name":"Mercury", "moons": 0 , "day_length":"58.6 days"})
db.planets.insert({"name":"Venus", "moons": 0 , "day_length":"241 days"})
db.planets.insert({"name":"Earth", "moons": 1 , "day_length":"1 day"})
db.planets.insert({"name":"Mars", "moons": 2 , "day_length":"24.5 hours"})
db.planets.insert({"name":"Jupiter", "moons": 53 , "day_length":"9.8 hours"})
db.planets.insert({"name":"Saturn", "moons": 53 , "day_length":"10.5 hours"})
db.planets.insert({"name":"Uranus", "moons": 27 , "day_length":"18 hours"})
db.planets.insert({"name":"Neptune", "moons": 13 , "day_length":"19 hours"})