//db.cities.remove()
db.cities.insert({"Houston":true})
db.cities.insert({"Atlanta":true})
db.cities.insert({"Baltimore":true})
db.cities.insert({"Tallahassee":true})
db.cities.insert({"Chicago":true})
db.cities.insert({"New York":false})
db.cities.insert({"Albany":false})
db.cities.insert({"Los Angeles":false})